 export const CHANGE_CODE_SHOW = 'CHANGE_CODE_SHOW';
 export const  REDUCTION_CODE_SHOW = 'REDUCTION_CODE_SHOW';
 export const  CHANGE_CUT_DWN_SHOW = 'CHANGE_CUT_DWN_SHOW';
 export const   GET_VOTE_DATA = 'GET_VOTE_DATA';
 export const  CHANGE_POP_SHOW = 'CHANGE_POP_SHOW';
 export const  CHANGE_ACT_CNT_SHOW = 'CHANGE_ACT_CNT_SHOW';
 export const  CHANGE_ACT_SET_SHOW = ' CHANGE_ACT_SET_SHOW';
 export const  CHANGE_USER_IS_SHOW = '  CHANGE_USER_IS_SHOW';